# Site specific settings
title: "Aquatints"
name: "Aquatints"
keywords: "Aquatints"
baseurl: ""
url: "https://aquatints.org"
description: "Just a few friends who do hackathons"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
ssl: true # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: 
twitter: 
facebook: 
github: aquatints
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
